### ISSUE TITLE
将日志处理的逻辑抽象成npm package

### ISSUE THREAD

**Issue by zzswang** [36node/shanghaibus-messenger#1]
## 背景

https://github.com/36node/shanghaibus-core/issues/62

### 背景

core，log 以及 chart 涉及到 kafka 日志的解析，这块需要统一处理一下，以适应未来可能的日志格式变化。

### 需求

1. 新建 shanghaibus-messager 工程，工程将实现kafka client包，涉及kafka连接，接收数据，测试等，可参考shanghaibus-core中现有代码。
2. 将现在core里面的 kafka handler里面的代码移至过去，完成日志的解析。
3. 完善 shanghaibus-messager readme 描述当前的log 日志及解析后的日志格式。

**Comment by magiccaptain** [comment]
已完成
